server:
  port: '8082'

spring:
  profiles:
    active: qa
---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp
    password: 'password'  //your password
  application:
    name: springbootlearn
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
#welcome:
#  message: Welcome from chandra kiran Bolla!

---

spring:
  config:
    activate:
      on-profile: qa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp_qa
    password: 'password'  //your password'
  application:
    name: springbootlearn
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'

  management:
    endpoints:
      web:
        exposure:
          include: "*"
          exclude: "env,beans"
#welcome:
#  message: Welcome from chandra kiran Bolla!

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp_prod
    password: 'password'  //your password
  application:
    name: springbootlearn
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
#welcome:
#  message: Welcome from chandra kiran Bolla!
